### ISSUE TITLE
Doesn't work in navbar navbar-collapse area on mobile 

### ISSUE THREAD

**Issue by markvital** [hyspace/typeahead.js-bootstrap3.less#29]
When I put typeahead in navbar-collapse arean, suggestions are not visible on mobile (suggestion list is cut from the bottom). When I move component to  'navbar-header' area everything works fine. I'm using Bootstrap v3.3.5.

Desktop:
<img width="813" alt="screen shot 2015-11-09 at 11 36 28 pm" src="https://cloud.githubusercontent.com/assets/742796/11056940/af4ea56c-873b-11e5-916a-32926c5bc3ab.png">

Mobile:
<img width="555" alt="screen shot 2015-11-09 at 11 36 46 pm" src="https://cloud.githubusercontent.com/assets/742796/11056939/af4d6c2e-873b-11e5-9b0a-94ecbd5f3817.png">

```
  <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">IconSearch</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse in">         
          <div class="input-group search-box">
            <input type="text" class="form-control search-form" placeholder="Search: man, kid, car, walk, sleep ..">
            <span class="input-group-btn">
              <button class="btn btn-default search-btn" type="button"><i class="fa fa-search fa-lg"></i></button>
            </span>
          </div><!-- /input-group -->       
        </div><!--/.nav-collapse -->
      </div>
    </nav>
```

**Comment by JoshRosen** [comment]
I think that this is a consequence of the 

``` css
.navbar-collapse.in {
  overflow-y: auto
}
```

rule in Bootstrap, since overriding that property to `overflow-y: visible` seems to fix things for me. My CSS is a bit rusty / limited, though, so I don't know whether this is an optimal solution.

**Comment by markvital** [comment]
@JoshRosen thank you, that solved the issue
